import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { dirname, join, resolve } from 'path';

class FileGenerator {
  static async ensureDirectory(dirPath) {
    if (!existsSync(dirPath)) {
      mkdirSync(dirPath, { recursive: true });
    }
  }

  static async writeFile(filePath, content, options = {}) {
    try {
      // Validate file path to prevent directory traversal
      const resolvedPath = resolve(filePath);
      const cwd = process.cwd();
      
      if (!resolvedPath.startsWith(cwd)) {
        throw new Error(`File path outside project directory: ${filePath}`);
      }

      // Ensure the directory exists
      const dir = dirname(resolvedPath);
      await this.ensureDirectory(dir);

      // Format the content if needed
      const formattedContent = options.format !== false ? 
        await this.formatTypeScript(content) : content;

      // Write the file
      writeFileSync(resolvedPath, formattedContent, 'utf8');
      
      return {
        success: true,
        path: resolvedPath,
        size: formattedContent.length
      };
    } catch (error) {
      return {
        success: false,
        path: filePath,
        error: error.message
      };
    }
  }

  static async writeTypeDefinitions(outputPath, content, config = {}) {
    const fileName = config.typesFileName || 'api.ts';
    const filePath = join(outputPath, fileName);
    
    return this.writeFile(filePath, content, { format: true });
  }

  static async writeApiClient(outputPath, content, config = {}) {
    const fileName = config.clientFileName || 'client.ts';
    const filePath = join(outputPath, fileName);
    
    return this.writeFile(filePath, content, { format: true });
  }

  static async writeDocumentation(projectPath, content, config = {}) {
    const fileName = config.docsFileName || 'README.md';
    const filePath = join(projectPath, fileName);
    
    return this.writeFile(filePath, content, { format: false }); // Don't format markdown as TypeScript
  }

  static async formatTypeScript(content) {
    // Basic TypeScript formatting
    // In a real implementation, you might use prettier or similar
    return content
      .split('\n')
      .map(line => {
        // Remove trailing whitespace
        return line.trimEnd();
      })
      .join('\n')
      .replace(/\n{3,}/g, '\n\n') // Reduce multiple empty lines to max 2
      .trim() + '\n'; // Ensure file ends with newline
  }

  static generateSummaryReport(results) {
    const successful = results.filter(r => r.success);
    const failed = results.filter(r => !r.success);

    const report = {
      total: results.length,
      successful: successful.length,
      failed: failed.length,
      files: successful.map(r => ({
        path: r.path,
        size: r.size
      })),
      errors: failed.map(r => ({
        path: r.path,
        error: r.error
      }))
    };

    return report;
  }

  static printGenerationReport(report, verbose = false) {
    console.log(`\n✅ Generated ${report.successful} of ${report.total} files successfully`);
    
    if (report.successful > 0) {
      console.log('\n📁 Generated files:');
      report.files.forEach(file => {
        const sizeKb = (file.size / 1024).toFixed(1);
        console.log(`   ${file.path} (${sizeKb}KB)`);
      });
    }

    if (report.failed > 0) {
      console.log(`\n❌ ${report.failed} files failed to generate:`);
      report.errors.forEach(error => {
        console.log(`   ${error.path}: ${error.error}`);
      });
    }

    if (verbose && report.successful > 0) {
      console.log('\n💡 Next steps:');
      console.log('   1. Check the generated TypeScript files compile: npx tsc --noEmit');
      console.log('   2. Import the types in your project: import { User } from "./types/api"');
      console.log('   3. Use the API client: import { ApiClient } from "./api/client"');
    }
  }

  static createGitignoreEntry() {
    const timestamp = new Date().toLocaleString();
    return `# ‼️ DO NOT EDIT ‼️ This section is automatically managed
# Generated by SpecJet CLI on ${timestamp}
# Uncomment the lines below if you want to ignore generated files
# src/types/api.ts
# src/api/client.ts
`;
  }

  static async writeGitignoreEntry(projectRoot, config = {}) {
    if (!config.updateGitignore) {
      return { success: true, skipped: true };
    }

    const gitignorePath = join(projectRoot, '.gitignore');
    const entry = this.createGitignoreEntry();

    try {
      let existingContent = '';
      if (existsSync(gitignorePath)) {
        existingContent = readFileSync(gitignorePath, 'utf8');
      }

      // Only add if not already present
      if (!existingContent.includes('Generated by SpecJet CLI')) {
        const newContent = existingContent + '\n' + entry;
        writeFileSync(gitignorePath, newContent, 'utf8');
        
        return {
          success: true,
          path: gitignorePath,
          action: 'updated'
        };
      }

      return {
        success: true,
        path: gitignorePath,
        action: 'already_present'
      };
    } catch (error) {
      return {
        success: false,
        path: gitignorePath,
        error: error.message
      };
    }
  }
}

export default FileGenerator;